### ISSUE TITLE
How to keep multiple builds/variants of a package or library?

### ISSUE THREAD

**Issue by JPGygax68** [vector-of-bool/libman#1]
3.1.2 states that a package must be unique within an index. Does that mean that, for example, i686 and x86_64 builds must be packaged separately?

**Comment by vector-of-bool** [comment]
Sorry for the _very lengthy_ delay, but the answer is "yes, they must be packaged separately."

The intended model is that a build system (or introspecting package manager) will emit the libman package and library files, which contain no information about the ABI of the libaries themselves. It is up to the package manager to emit an index file that refers to packages that have been built with a consistent ABI. For example, there will be distinct `.lmp` files for the 32-bit and 64-bit builds of each package in a tree, and the package manager will emit an individual `INDEX.lmi` file for whichever ABI has been requested.

In the case of multi-conf build systems (which CMake can support, for example), it is possible for the package manager to emit an `INDEX.debug.lmi` and `INDEX.release.lmi`, and then have CMake import _both_, and setting the `IMPORTED_LOCATION_DEBUG` and `IMPORTED_LOCATION_RELEASE` appropriately. (This is currently the _intended_ design but has not yet been implemented in `libman.cmake`,)

**Comment by JPGygax68** [comment]
Thanks @vector-of-bool ! It's been a while since I read the libman docs. I hope I'll be able to get started using it at last.
