### ISSUE TITLE
Docs not online?

### ISSUE THREAD

**Issue by JPGygax68** [vector-of-bool/libman#2]
I've built the docs from the sources, but it would be nice to be able to refer to an online copy, especially as they contain invaluable information about CMake not easy to find elsewhere.

**Comment by vector-of-bool** [comment]
Yes, actually. The documentation is rendered on-the-fly using the CSSWG's online Bikeshed renderer here: https://api.csswg.org/bikeshed/?force=1&url=https://raw.githubusercontent.com/vector-of-bool/libman/develop/data/spec.bs

Note that this page will automatically update to reflect whatever is at `develop`.

**Comment by JPGygax68** [comment]
@vector-of-bool : Thanks! I looked for a bit but couldn't find it.
